// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversiteYonetimSistemi.DAL.Context;

#nullable disable

namespace UniversiteYonetimSistemi.DAL.Migrations
{
    [DbContext(typeof(UniversiteDbContext))]
    [Migration("20250111111215_firstMig")]
    partial class firstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Bolum", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BolumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FakulteID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ders", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BolumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DersAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kredi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.DersAtama", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DersID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OgretimGorevlisiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OgretimGorevlisiID1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DersID");

                    b.HasIndex("OgretimGorevlisiID");

                    b.HasIndex("OgretimGorevlisiID1");

                    b.ToTable("DersAtamalari");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Fakulte", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FakulteAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Fakulteler");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Kullanici", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ogrenci", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BolumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.OgrenciDersKayit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DersID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Not")
                        .HasColumnType("real");

                    b.Property<Guid>("OgrenciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DersID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("OgrenciDersKayitlari");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.OgretimGorevlisi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BolumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.ToTable("OgretimGorevlileri");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Bolum", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Fakulte", "Fakulte")
                        .WithMany("Bolumler")
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ders", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Bolum", "Bolum")
                        .WithMany("Dersler")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.DersAtama", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Ders", "Ders")
                        .WithMany("DersAtamalari")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.OgretimGorevlisi", "OgretimGorevlisi")
                        .WithMany()
                        .HasForeignKey("OgretimGorevlisiID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.OgretimGorevlisi", null)
                        .WithMany("DersAtamalari")
                        .HasForeignKey("OgretimGorevlisiID1");

                    b.Navigation("Ders");

                    b.Navigation("OgretimGorevlisi");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ogrenci", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.OgrenciDersKayit", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Ders", "Ders")
                        .WithMany("OgrenciDersKayitlari")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersKayitlari")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.OgretimGorevlisi", b =>
                {
                    b.HasOne("UniversiteYonetimSistemi.Entities.Models.Bolum", "Bolum")
                        .WithMany("OgretimGorevlileri")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Bolum", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Ogrenciler");

                    b.Navigation("OgretimGorevlileri");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ders", b =>
                {
                    b.Navigation("DersAtamalari");

                    b.Navigation("OgrenciDersKayitlari");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Fakulte", b =>
                {
                    b.Navigation("Bolumler");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersKayitlari");
                });

            modelBuilder.Entity("UniversiteYonetimSistemi.Entities.Models.OgretimGorevlisi", b =>
                {
                    b.Navigation("DersAtamalari");
                });
#pragma warning restore 612, 618
        }
    }
}
